channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=23.3.1
- pip:
  - mlflow==2.9.2
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - packaging==23.2
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.12.0
name: mlflow-env
